#!/bin/bash

cd downloads

mkdir brats2020_184subjects_noaugmentation_multiplesegmentationchannels_min15percentcoverage
mkdir brats2020_184subjects_noaugmentation_singlesegmentationchannel_min15percentcoverage
mkdir brats2020_184subjects_rotationaugmentation_multiplesegmentationchannels_min15percentcoverage
mkdir brats2020_184subjects_rotationaugmentation_singlesegmentationchannel_min15percentcoverage
mkdir brats2020_23subjects_noaugmentation_multiplesegmentationchannels_min15percentcoverage
mkdir brats2020_23subjects_noaugmentation_singlesegmentationchannel_min15percentcoverage
mkdir brats2020_23subjects_rotationaugmentation_multiplesegmentationchannels_min15percentcoverage
mkdir brats2020_23subjects_rotationaugmentation_singlesegmentationchannel_min15percentcoverage
mkdir brats2020_313subjects_noaugmentation_multiplesegmentationchannels_min15percentcoverage
mkdir brats2020_313subjects_noaugmentation_singlesegmentationchannel_min15percentcoverage
mkdir brats2020_313subjects_rotationaugmentation_multiplesegmentationchannels_min15percentcoverage
mkdir brats2020_313subjects_rotationaugmentation_singlesegmentationchannel_min15percentcoverage
mkdir brats2020_369subjects_noaugmentation_multiplesegmentationchannels_min15percentcoverage
mkdir brats2020_369subjects_noaugmentation_singlesegmentationchannel_min15percentcoverage
mkdir brats2020_369subjects_rotationaugmentation_multiplesegmentationchannels_min15percentcoverage
mkdir brats2020_369subjects_rotationaugmentation_singlesegmentationchannel_min15percentcoverage
mkdir brats2020_46subjects_noaugmentation_multiplesegmentationchannels_min15percentcoverage
mkdir brats2020_46subjects_noaugmentation_singlesegmentationchannel_min15percentcoverage
mkdir brats2020_46subjects_rotationaugmentation_multiplesegmentationchannels_min15percentcoverage
mkdir brats2020_46subjects_rotationaugmentation_singlesegmentationchannel_min15percentcoverage
mkdir brats2020_92subjects_noaugmentation_multiplesegmentationchannels_min15percentcoverage
mkdir brats2020_92subjects_noaugmentation_singlesegmentationchannel_min15percentcoverage
mkdir brats2020_92subjects_rotationaugmentation_multiplesegmentationchannels_min15percentcoverage
mkdir brats2020_92subjects_rotationaugmentation_singlesegmentationchannel_min15percentcoverage

for directory in "/local/data1/andek67/ProgressiveGAN/downloads/"brats2020*singlesegmentation*; 
do
    echo "$directory "
    cd $directory
    mkdir T1 T2 T1CE FLAIR Seg
done

for directory in "/local/data1/andek67/ProgressiveGAN/downloads/"brats2020*multiplesegmentation*; 
do
    echo "$directory "
    cd $directory
    mkdir T1 T2 T1CE FLAIR Seg1 Seg2 Seg3
done



